# Generated by Django 3.1.3 on 2020-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300)),
                ('Priority', models.IntegerField(choices=[(1, 'DANGER'), (2, 'WARNING'), (3, 'RELAX')], null=True)),
                ('ExecutionDate', models.DateTimeField()),
            ],
        ),
    ]
