# Generated by Django 3.1.3 on 2020-11-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.IntegerField(choices=[(1, 'DANGER'), (2, 'WARNING'), (3, 'RELAX')], null=True),
        ),
    ]
