# Generated by Django 3.1.3 on 2020-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ExecutionDate',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Priority',
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'NO PRIORITY'), (1, 'DANGER'), (2, 'WARNING'), (3, 'RELAX')], null=True),
        ),
    ]
